version: 2.1

orbs:
  node: circleci/node@5.1.0
jobs:
  build-and-push:
    executor: node/default
    environment:
      DOCKER_IMAGE: circleci-test-react
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Log in to DockerHub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
      - run:
          name: Build docker image
          command: docker build -t anhntdocker/$IMAGE_NAME:latest .
      - run:
          name: Push docker image to DockerHub
          command: docker push anhntdocker/$IMAGE_NAME:latest
#   deploy:
#     executor: docker/docker
#     steps:
#       - add_ssh_keys:
#           fingerprints:
#             - $SSH_KEY_FINGERPRINT
#       - run: ssh -oStrictHostKeyChecking=no $DEPLOYED_USER@$DEPLOYED_SERVER './deploy.sh'
workflows:
  commit:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - "node/test"
          filters:
            branches:
              only:
                - master
      # - deploy:
      #    requires:
      #     - build-and-push