version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0
jobs:
  node/test:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/google-cloud-ci-cd-react
          paths:
            - .
  build-and-push: # this can be any name you choose
    environment:
      DOCKER_IMAGE: circleci-react-test
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$DOCKER_IMAGE
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_LOGIN/$DOCKER_IMAGE
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
     - add_ssh_keys:
         fingerprints:
           - "f1:be:46:63:91:ff:db:c1:4f:35:25:82:7a:1e:65:b4"
     - run:
        name: Access SSH Key 
        command: ssh -oStrictHostKeyChecking=no circleci@139.59.238.79
     - run:
        name: Docker Compose Command
        command: |
          docker-compose stop
          docker-compose rm -f
          docker-compose pull
          docker-compose up -d
    #  - run: ssh -oStrictHostKeyChecking=no $HOST_USER@$HOST './deploy.sh'

workflows:
  commit:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - "node/test"
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-and-push
