# my configx
version: 2.1
orbs:
    node: circleci/node@3.0.0
    docker: circleci/docker@1.4.0

jobs:
    build-and-push:
        environment:
            DOCKER_IMAGE: anhnt/google-cloud-ci-cd-react
            DOCKER_TAG: latest
            DOCKER_REGISTRY_USERNAME_IMAGE: anhntdocker/google-cloud-ci-cd-react
        executor: docker/docker
        steps:
            - setup_remote_docker
            # - checkout
            - docker/check
            # - docker/build:
            #       image: $DOCKER_IMAGE
            #       tag: $DOCKER_TAG
            # - docker/push:
            #       digest-path: /tmp/digest.txt
            #       image: $DOCKER_IMAGE
            #       tag: $DOCKER_TAG
            - run:
                name: Build application Docker image
                command: |
                    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
                    docker build --cache-from=$DOCKER_IMAGE:$DOCKER_TAG -t $DOCKER_IMAGE:$DOCKER_TAG .
            - run:
                  name: Publish Docker Image to Docker Hub
                  command: |
                      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
                      docker tag $DOCKER_IMAGE $DOCKER_REGISTRY_USERNAME_IMAGE
                      docker push $DOCKER_IMAGE:$DOCKER_TAG
            - run:
                  command: |
                      echo "Digest is: $(</tmp/digest.txt)"

workflows:
    my-pipeline:
        jobs:
            - node/test
            - build-and-push:
                  requires:
                      - node/test
                  filters:
                      branches:
                          only:
                              - master
