version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    environment:
      USER: root
      IP: 139.59.238.79
    docker:
      - image: circleci-myreact
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main