pipeline {
    agent any
    tools {
        nodejs 'nodejs'
    }
    parameters {
        choice(name:'VERSION', choices:['1.0', '1.1', '1.2'], description:'Choose the version of the project')

        booleanParam(name :'executeTests', description:'Execute the tests', defaultValue:false)
    }

    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            // sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                // sh 'npm run test'
                echo 'Test'
            }
        }
        stage('Build Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-account-username-password', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    sh 'docker build -t anhntdocker/sample-react-app-jenkins-ec2 .'
                    sh "echo $PASS | docker login -u $USER --password-stdin"
                    sh 'docker push anhntdocker/sample-react-app-jenkins-ec2'
                }
            }
        }
    }
}
