pipeline {
    agent none
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:lts-bullseye-slim',
                }
            }
            steps {
                sh 'npm install'
            }
        }
    }
}
