name: demo CI
on: [push]
jobs:
  # JavaScript - ReactJS
  connect-to-jenkins:
    runs-on: ubuntu-latest
    name: javascript:jenkins-static-image-pipeline-test
    steps:
      - uses: actions/checkout@v2
      - name: Jenkins pipeline with the static image
        id: jenkins_pipeline_image
        uses: jenkinsci/jfr-static-image-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
          baseImage: node:18.3.0
